trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.9.8'
  workingDirectory: 'env/dev'
  serviceConnection: 'sc-identity-federation'

stages:
- stage: ValidateAndPlan
  displayName: 'Terraform PR Validation'
  jobs:
  - job: ValidateAndPlan
    displayName: 'Validate and Plan'
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '$(terraformVersion)'

    - task: AzureCLI@2
      displayName: 'Terraform Init / Fmt / Validate / Plan'
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd $(workingDirectory)

          terraform init -backend-config=backend.hcl
          terraform fmt -check -recursive
          terraform validate
          terraform plan -var-file=terraform.tfvars