# =========================================================
# Stage 3 - Apply
# Runs ONLY when code is merged/pushed to main
# =========================================================
- stage: Apply
  displayName: 'Terraform Apply'
  dependsOn: Plan
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  jobs:
  - deployment: ApplyDeployment
    displayName: 'Apply Terraform'

    environment:
      name: dev-azure-apply

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          - download: current
            artifact: tfplan

          - task: AzureCLI@2
            displayName: 'Terraform Apply'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                cd $(workingDirectory)

                terraform init

                cp $(Pipeline.Workspace)/tfplan/tfplan ./tfplan

                terraform apply -auto-approve tfplan